<?xml version="1.0" ?>
<!DOCTYPE cart [
	<!ELEMENT item (itemID,quantity)>
	<!ATTLIST item id ID #REQUIRED>
	<!ELEMENT itemID (#PCDATA)>
	<!ELEMENT quantity (#PCDATA)>
]>
<cart>
	<item id="cart_0">
		<itemID>item_0</itemID>
		<quantity>2</quantity>
	</item>
	<item id="cart_1">
		<itemID>item_3</itemID>
		<quantity>1</quantity>
	</item>
</cart>