<?xml version="1.0" ?>
<!DOCTYPE sales [
	<!ELEMENT item (itemID)>
	<!ATTLIST item id ID #REQUIRED>
	<!ELEMENT itemID (#PCDATA)>
]>
<sales>
	<item id="sale_0">
		<itemID>item_0</itemID>
	</item>
	<item id="sale_1">
		<itemID>item_3</itemID>
	</item>
	<item id="sale_2">
		<itemID>item_5</itemID>
	</item>
</sales>